<?php

declare(strict_types=1);

require_once dirname(__DIR__) . "/bootstrap/app.php";

$router = new Router();

$router->get("/", "HomeController@index");
$router->get("/login", "AuthController@showLoginForm", ["guest"]);
$router->post("/login", "AuthController@login", ["guest"]);
$router->post("/logout", "AuthController@logout", ["auth"]);
$router->get("/dashboard", "DashboardController@index", ["auth"]);
$router->get("/cashier", "CashierController@index", ["auth"]);
$router->post("/cashier/start", "CashierController@start", ["auth"]);
$router->post("/cashier/close", "CashierController@close", ["auth"]);
$router->get("/pos", "PosController@index", ["auth", "permission:p_2", "cashier"]);
$router->get("/pos/slots/{slot}", "PosController@switchSlot", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/slots/{slot}/clear", "PosController@clearSlot", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/lookup/name", "PosController@lookupByName", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/lookup/code", "PosController@lookupByCode", ["auth", "permission:p_2", "cashier"]);
$router->get("/api/pos/salespeople/{id}", "PosController@salesPersonLookup", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/customer", "PosController@selectCustomer", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/seller", "PosController@selectSalesPerson", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/items", "PosController@addItem", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/items/imei-bulk", "PosController@addBulkImeiItems", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/items/{id}", "PosController@updateLine", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/items/{id}/delete", "PosController@removeLine", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/reset", "PosController@resetCart", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/payment", "PosController@updatePayment", ["auth", "permission:p_2", "cashier"]);
$router->post("/pos/checkout", "PosController@checkout", ["auth", "permission:p_2", "cashier"]);
$router->get("/pos/receipts/{billnumber}", "PosController@receipt", ["auth", "permission:p_2"]);
$router->get("/pos/receipts/{billnumber}/print", "PosController@printReceipt", ["auth", "permission:p_2"]);
$router->get("/pos/receipts/{billnumber}/barcodes", "PosController@barcodeLabels", ["auth", "permission:p_2"]);
$router->post("/pos/receipts/{billnumber}/barcodes/print", "PosController@printBarcodeLabels", ["auth", "permission:p_2"]);
$router->get("/settings", "SettingsController@index", ["auth", "permission:p_63"]);
$router->get("/settings/users", "UserManagementController@index", ["auth", "permission:p_65"]);
$router->get("/settings/users/create", "UserManagementController@create", ["auth", "permission:p_64"]);
$router->post("/settings/users", "UserManagementController@store", ["auth", "permission:p_64"]);
$router->post("/settings/users/{id}/status", "UserManagementController@updateStatus", ["auth", "permission:p_65"]);
$router->get("/settings/shops", "ShopController@index", ["auth", "permission:p_71"]);
$router->get("/settings/shops/create", "ShopController@create", ["auth", "permission:p_70"]);
$router->post("/settings/shops", "ShopController@store", ["auth", "permission:p_70"]);
$router->get("/settings/shops/{id}/edit", "ShopController@edit", ["auth", "permission:p_71"]);
$router->post("/settings/shops/{id}", "ShopController@update", ["auth", "permission:p_71"]);
$router->get("/settings/profile", "UserProfileController@edit", ["auth"]);
$router->post("/settings/profile", "UserProfileController@updateDetails", ["auth"]);
$router->post("/settings/profile/password", "UserProfileController@updatePassword", ["auth"]);
$router->get("/settings/privileges", "PrivilegeController@index", ["auth", "permission:p_67"]);
$router->post("/settings/privileges", "PrivilegeController@store", ["auth", "permission:p_67"]);
$router->post("/settings/privileges/{id}", "PrivilegeController@update", ["auth", "permission:p_67"]);
$router->get("/settings/privileges/{id}/functions", "PrivilegeController@editFunctions", ["auth", "permission:p_67"]);
$router->post("/settings/privileges/{id}/functions", "PrivilegeController@updateFunctions", ["auth", "permission:p_67"]);
$router->get("/settings/privileges/{id}/reports", "PrivilegeController@editReports", ["auth", "permission:p_67"]);
$router->post("/settings/privileges/{id}/reports", "PrivilegeController@updateReports", ["auth", "permission:p_67"]);
$router->get("/settings/user-privileges", "UserPrivilegeController@index", ["auth", "permission:p_68"]);
$router->post("/settings/user-privileges/{id}", "UserPrivilegeController@update", ["auth", "permission:p_68"]);
$router->get("/categories", "ProductCategoryController@index", ["auth", "permission:p_18"]);
$router->post("/categories", "ProductCategoryController@store", ["auth", "permission:p_18"]);
$router->post("/categories/{id}", "ProductCategoryController@update", ["auth", "permission:p_18"]);
$router->post("/categories/{id}/delete", "ProductCategoryController@destroy", ["auth", "permission:p_18"]);
$router->get("/item-colors", "ItemColorController@index", ["auth", "permission:p_19"]);
$router->post("/item-colors", "ItemColorController@store", ["auth", "permission:p_19"]);
$router->post("/item-colors/{id}", "ItemColorController@update", ["auth", "permission:p_19"]);
$router->post("/item-colors/{id}/delete", "ItemColorController@destroy", ["auth", "permission:p_19"]);
$router->get("/operators", "RechargeOperatorController@index", ["auth", "permission:p_22"]);
$router->post("/operators", "RechargeOperatorController@store", ["auth", "permission:p_22"]);
$router->post("/operators/{id}", "RechargeOperatorController@update", ["auth", "permission:p_22"]);
$router->post("/api/pos/customers", "PosHelperController@customerLookup", ["auth"]);
$router->post("/api/pos/items/by-name", "PosHelperController@itemLookupByName", ["auth"]);
$router->post("/api/pos/items/by-code", "PosHelperController@itemLookupByCode", ["auth"]);
$router->get("/api/items/by-category", "StockSearchController@itemsByCategory", ["auth", "permission:p_17"]);
$router->get("/items", "ItemController@index", ["auth", "permission:p_16"]);
$router->get("/items/create", "ItemController@create", ["auth", "permission:p_15"]);
$router->post("/items", "ItemController@store", ["auth", "permission:p_15"]);
$router->get("/items/{id}/edit", "ItemController@edit", ["auth", "permission:p_16"]);
$router->post("/items/{id}", "ItemController@update", ["auth", "permission:p_16"]);
$router->get("/item-alerts", "StockAlertController@index", ["auth", "permission:p_52"]);
$router->post("/item-alerts", "StockAlertController@store", ["auth", "permission:p_52"]);
$router->post("/item-alerts/{id}", "StockAlertController@update", ["auth", "permission:p_52"]);
$router->post("/item-alerts/{id}/delete", "StockAlertController@destroy", ["auth", "permission:p_52"]);
$router->get("/items/search", "StockSearchController@index", ["auth", "permission:p_17"]);
$router->get("/suppliers", "SupplierController@index", ["auth", "permission:p_26"]);
$router->get("/suppliers/create", "SupplierController@create", ["auth", "permission:p_25"]);
$router->post("/suppliers", "SupplierController@store", ["auth", "permission:p_25"]);
$router->get("/suppliers/{id}/edit", "SupplierController@edit", ["auth", "permission:p_26"]);
$router->post("/suppliers/{id}", "SupplierController@update", ["auth", "permission:p_26"]);
$router->get("/supplier-accounts", "AccountBalanceController@suppliers", ["auth", "permission:p_27"]);
$router->get("/supplier-credit-balances", "AccountBalanceController@supplierCashCredits", ["auth", "permission:p_28"]);
$router->post("/supplier-credit-balances/refresh", "AccountBalanceController@refreshSupplierCashCredits", ["auth", "permission:p_28"]);
$router->get("/supplier-payments", "PaymentController@supplierForm", ["auth", "permission:p_29", "cashier"]);
$router->get("/reports/supplier-payments", "FinanceReportController@supplierPayments", ["auth", "permission:r_15"]);
$router->get("/api/supplier-payments/details", "PaymentController@supplierDetails", ["auth", "permission:p_29", "cashier"]);
$router->post("/supplier-payments", "PaymentController@storeSupplierPayment", ["auth", "permission:p_29", "cashier"]);
$router->get("/customers", "CustomerController@index", ["auth", "permission:p_37"]);
$router->get("/customers/create", "CustomerController@create", ["auth", "permission:p_36"]);
$router->post("/customers", "CustomerController@store", ["auth", "permission:p_36"]);
$router->get("/customers/{id}/edit", "CustomerController@edit", ["auth", "permission:p_37"]);
$router->post("/customers/{id}", "CustomerController@update", ["auth", "permission:p_37"]);
$router->post("/customers/{id}/status", "CustomerController@updateStatus", ["auth", "permission:p_37"]);
$router->get("/customer-accounts", "AccountBalanceController@customers", ["auth", "permission:p_39"]);
$router->get("/customer-credit-balances", "AccountBalanceController@customerCashCredits", ["auth", "permission:p_40"]);
$router->post("/customer-credit-balances/refresh", "AccountBalanceController@refreshCustomerCashCredits", ["auth", "permission:p_40"]);
$router->get("/customer-payments", "PaymentController@customerForm", ["auth", "permission:p_41", "cashier"]);
$router->get("/reports/customer-payments", "FinanceReportController@customerPayments", ["auth", "permission:r_19"]);
$router->get("/api/customer-payments/details", "PaymentController@customerDetails", ["auth", "permission:p_41", "cashier"]);
$router->post("/customer-payments", "PaymentController@storeCustomerPayment", ["auth", "permission:p_41", "cashier"]);

$router->dispatch($_SERVER["REQUEST_URI"], $_SERVER["REQUEST_METHOD"]);
