<?php

declare(strict_types=1);

class PermissionCatalog
{
    public static function functionPermissions(): array
    {
        return [
            "p_1" => "Dashboard View",
            "p_2" => "POS Operation",
            "p_3" => "Repair Job Create",
            "p_4" => "Repair Process Operation",
            "p_5" => "Repair Job Bill Create",
            "p_6" => "Repair Item Release And Payment",
            "p_7" => "Repair Center Search",
            "p_8" => "Check Order Status",
            "p_9" => "Re-Print Job Receipt",
            "p_10" => "Repair Job Bills",
            "p_11" => "Repair Center Manage",
            "p_12" => "Manage Customer Items",
            "p_13" => "Manage Common Fault List",
            "p_14" => "Shop Item Manage",
            "p_15" => "Add Item",
            "p_16" => "Edit Item",
            "p_17" => "Search Item",
            "p_18" => "Manage Category",
            "p_19" => "Manage Item Color",
            "p_20" => "IMEI Number Checking",
            "p_21" => "Recharge Cards",
            "p_22" => "Manage Operator",
            "p_23" => "Manage Cards",
            "p_24" => "Suppliers",
            "p_25" => "Add New Supplier",
            "p_26" => "Suppliers List",
            "p_27" => "Suppliers Account Balance",
            "p_28" => "Suppliers Credit Balance",
            "p_29" => "Supplier Payment And GRN Payment",
            "p_30" => "Bill Details",
            "p_31" => "Daily Bills",
            "p_32" => "Find Bill",
            "p_33" => "Customer Bill Return",
            "p_34" => "Customer Return Activity",
            "p_35" => "Customers",
            "p_36" => "Add Customer",
            "p_37" => "Manage Customer",
            "p_38" => "Search Customer",
            "p_39" => "Customer Account Balance",
            "p_40" => "Customer Credit Balance",
            "p_41" => "Customer Payment",
            "p_42" => "Purchases",
            "p_43" => "Add GRN",
            "p_44" => "Reserved Purchase Permission",
            "p_45" => "Find GRN",
            "p_46" => "Print Barcode Label",
            "p_47" => "Stocks",
            "p_48" => "Stock Transfer",
            "p_49" => "Transfer Note",
            "p_50" => "Transfer Received",
            "p_51" => "Return Stock",
            "p_52" => "Item Alert Configuration",
            "p_53" => "Stock Removing",
            "p_54" => "Stock Adjust",
            "p_55" => "Edit Prices",
            "p_56" => "Cashier",
            "p_57" => "Add Expense Or Cash In",
            "p_58" => "Cashier Duty Off",
            "p_59" => "Cashier Duty On",
            "p_60" => "Add Expenses Account",
            "p_61" => "Add Cash In Account",
            "p_62" => "Reports View",
            "p_63" => "User Management",
            "p_64" => "Add User",
            "p_65" => "Manage User",
            "p_66" => "Permission Management",
            "p_67" => "Function Permission",
            "p_68" => "User Function Mapping",
            "p_69" => "Manage Shops",
            "p_70" => "Add Shops",
            "p_71" => "Shop List Or Edit",
            "p_72" => "System Cashier Point Management",
            "p_73" => "Add Cashier Point",
            "p_74" => "View Cashier Details",
            "p_75" => "Transfer Damage Item Box",
            "p_76" => "Damage Return Process",
            "p_77" => "SMS Broadcast",
        ];
    }

    public static function reportPermissions(): array
    {
        return [
            "r_1" => "User Report",
            "r_2" => "System User List",
            "r_3" => "User Sale List",
            "r_4" => "Security Log",
            "r_5" => "Product Report",
            "r_6" => "Product Category List",
            "r_7" => "Product List",
            "r_8" => "System Whole Stock List",
            "r_9" => "Stock List By Category",
            "r_10" => "Available Stock List",
            "r_11" => "Finished Stock List",
            "r_12" => "Suppliers Report",
            "r_13" => "System Supplier List",
            "r_14" => "Supplier Account Balance List",
            "r_15" => "Supplier Account Full Details",
            "r_16" => "Customer Report",
            "r_17" => "System Customer List",
            "r_18" => "Customer Account Balance List",
            "r_19" => "Customer Payment Details",
            "r_20" => "Sales Report",
            "r_21" => "Shop Sale Report",
            "r_22" => "Under Cost Item Report",
            "r_23" => "Over Cost Item Report",
            "r_24" => "Category Wise Sales",
            "r_25" => "Item Wise Sales",
            "r_26" => "Phone Sales Report",
            "r_27" => "Category And Item Wise Sales",
            "r_28" => "Best Sales Report",
            "r_29" => "GRN Report",
            "r_30" => "GRN List",
            "r_31" => "GRN Detail",
            "r_32" => "Reorder Item Report",
            "r_33" => "Cashier Report",
            "r_34" => "Shop Transaction List Report",
            "r_35" => "Shop Open Close Balance Report",
            "r_36" => "Shop Expenses Report",
            "r_37" => "Account Wise Expenses Report",
            "r_38" => "Shop Sale Profit Report",
            "r_39" => "Repair Center Report",
            "r_40" => "Repair Job List",
            "r_41" => "In Progress Job List",
            "r_42" => "Bill Created Job List",
            "r_43" => "Reopened Job List",
            "r_44" => "Repair Full Log Report",
            "r_45" => "Reports For Records Edit",
            "r_46" => "Price Edit Log",
            "r_47" => "Stock Adjust Log",
            "r_48" => "Stock Removing Log",
        ];
    }
}
